# -*- coding: utf-8 -*-
"""app

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Od4GQszUFFawEfPtBDq55K--PL88MdoK
"""

from flask import Flask,jsonify,request
import numpy as np
import pandas as pd
import datetime

from CS2_final import final
import flask

app=Flask(__name__)

final_object=final()
######################################

######################################

@app.route('/',methods=['GET'])
def index():
  return flask.render_template('index.html')

@app.route('/predict',methods=['POST'])
def predict():
  index=request.from.to_dict()['Enter index of the file']
  rec_id,predicted_labels,end_time=final_object.predict(int(index))
  return flask.render_template('out.html',Recording_id=rec_id,predicted=predicted_labels,time=end_time)

if __name__='__main__':
  app.run(debug=True)